# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        # Version range or exact version of a Python version to use, using SemVer's version range syntax.
        python-version: 3.7.6
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
    - name: Install google-chrome dependencies
      run: |
        wget https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        chmod +x ./chromedriver
        export PATH=`pwd`:$PATH
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
    - name: Set system time
      run: sudo date +%T -s "13:14:00"
    - name: Test everything end-to-end
      run: |
        chmod +x ./integration_test/test.sh && ./integration_test/test.sh
